-- ============================================================
-- Bisecco — Seed des 290 métiers (source: lib/metiers.ts du V2)
-- ============================================================
-- À exécuter dans Supabase SQL Editor.
-- Idempotent : peut être ré-exécuté sans danger (ON CONFLICT)
-- ============================================================

BEGIN;

-- 1. Mise à jour de la CHECK constraint pour accepter les nouvelles catégories V2
ALTER TABLE public.metiers DROP CONSTRAINT IF EXISTS metiers_category_check;
ALTER TABLE public.metiers ADD CONSTRAINT metiers_category_check
  CHECK (category IN ('Alimentation', 'Bâtiment', 'Fabrication / Production', 'Services'));

-- 2. Upsert de 174 métiers
INSERT INTO public.metiers (name, slug, category, icon) VALUES
  ('Boulanger', 'boulanger', 'Alimentation', '🥖'),
  ('Pâtissier', 'patissier', 'Alimentation', '🧁'),
  ('Chocolatier', 'chocolatier', 'Alimentation', '🍫'),
  ('Confiseur', 'confiseur', 'Alimentation', '🍬'),
  ('Glacier', 'glacier', 'Alimentation', '🍦'),
  ('Biscuitier', 'biscuitier', 'Alimentation', '🍪'),
  ('Traiteur', 'traiteur', 'Alimentation', '🍴'),
  ('Boucher', 'boucher', 'Alimentation', '🥩'),
  ('Charcutier', 'charcutier', 'Alimentation', '🥓'),
  ('Poissonnier', 'poissonnier', 'Alimentation', '🐟'),
  ('Fromager', 'fromager', 'Alimentation', '🧀'),
  ('Laitier', 'laitier', 'Alimentation', '🥛'),
  ('Brasseur artisanal', 'brasseur-artisanal', 'Alimentation', '🍺'),
  ('Distillateur', 'distillateur', 'Alimentation', '🥃'),
  ('Liquoriste', 'liquoriste', 'Alimentation', '🍶'),
  ('Torréfacteur', 'torrefacteur', 'Alimentation', '☕'),
  ('Fabricant de glaces', 'fabricant-de-glaces', 'Alimentation', '🍨'),
  ('Pizzaïolo', 'pizzaiolo', 'Alimentation', '🍕'),
  ('Crêpier', 'crepier', 'Alimentation', '🥞'),
  ('Nougatier', 'nougatier', 'Alimentation', '🍯'),
  ('Apiculteur-transformateur', 'apiculteur-transformateur', 'Alimentation', '🐝'),
  ('Fabricant de produits bio', 'fabricant-de-produits-bio', 'Alimentation', '🌱'),
  ('Fabricant de chocolats', 'fabricant-de-chocolats', 'Alimentation', '🍫'),
  ('Fabricant de produits régionaux', 'fabricant-de-produits-regionaux', 'Alimentation', '🇫🇷'),
  ('Fabricant de spiritueux', 'fabricant-de-spiritueux', 'Alimentation', '🥃'),
  ('Saunier', 'saunier', 'Alimentation', '🧂'),
  ('Maçon', 'macon', 'Bâtiment', '🧱'),
  ('Couvreur', 'couvreur', 'Bâtiment', '🏠'),
  ('Zingueur', 'zingueur', 'Bâtiment', '🔨'),
  ('Charpentier', 'charpentier', 'Bâtiment', '🪵'),
  ('Menuisier', 'menuisier', 'Bâtiment', '🪚'),
  ('Éclairagiste', 'eclairagiste', 'Bâtiment', '💡'),
  ('Plombier', 'plombier', 'Bâtiment', '🔧'),
  ('Chauffagiste', 'chauffagiste', 'Bâtiment', '🔥'),
  ('Climaticien', 'climaticien', 'Bâtiment', '❄️'),
  ('Frigoriste', 'frigoriste', 'Bâtiment', '🧊'),
  ('Électricien', 'electricien', 'Bâtiment', '⚡'),
  ('Domoticien', 'domoticien', 'Bâtiment', '🏡'),
  ('Cuisiniste', 'cuisiniste', 'Bâtiment', '🍴'),
  ('Carreleur', 'carreleur', 'Bâtiment', '◼️'),
  ('Peintre en bâtiment', 'peintre-en-batiment', 'Bâtiment', '🎨'),
  ('Décorateur intérieur', 'decorateur-interieur', 'Bâtiment', '🛋️'),
  ('Façadier', 'facadier', 'Bâtiment', '🏗️'),
  ('Étancheur', 'etancheur', 'Bâtiment', '💧'),
  ('Plâtrier', 'platrier', 'Bâtiment', '🧰'),
  ('Staffeur', 'staffeur', 'Bâtiment', '🏛️'),
  ('Serrurier', 'serrurier', 'Bâtiment', '🔐'),
  ('Métallier', 'metallier', 'Bâtiment', '🔩'),
  ('Ferronnier', 'ferronnier', 'Bâtiment', '⚒️'),
  ('Tailleur de pierre', 'tailleur-de-pierre', 'Bâtiment', '⛏️'),
  ('Marbrier', 'marbrier', 'Bâtiment', '💎'),
  ('Installateur sanitaire', 'installateur-sanitaire', 'Bâtiment', '🚿'),
  ('Canalisateur', 'canalisateur', 'Bâtiment', '🚰'),
  ('Terrassier', 'terrassier', 'Bâtiment', '🚜'),
  ('Pisciniste', 'pisciniste', 'Bâtiment', '🏊'),
  ('Installateur photovoltaïque', 'installateur-photovoltaique', 'Bâtiment', '☀️'),
  ('Installateur thermique', 'installateur-thermique', 'Bâtiment', '🌡️'),
  ('Storiste', 'storiste', 'Bâtiment', '🪟'),
  ('Agenceur', 'agenceur', 'Bâtiment', '📐'),
  ('Poseur de cuisines', 'poseur-de-cuisines', 'Bâtiment', '🍳'),
  ('Poseur de sols', 'poseur-de-sols', 'Bâtiment', '🟫'),
  ('Parqueteur', 'parqueteur', 'Bâtiment', '🪵'),
  ('Chapiste', 'chapiste', 'Bâtiment', '⬜'),
  ('Vitrier', 'vitrier', 'Bâtiment', '🪟'),
  ('Miroitier', 'miroitier', 'Bâtiment', '🪞'),
  ('Constructeur bois', 'constructeur-bois', 'Bâtiment', '🏠'),
  ('Constructeur métallique', 'constructeur-metallique', 'Bâtiment', '🏗️'),
  ('Bardeur', 'bardeur', 'Bâtiment', '🏗️'),
  ('Échafaudeur', 'echafaudeur', 'Bâtiment', '🪜'),
  ('Ascensoriste', 'ascensoriste', 'Bâtiment', '🛗'),
  ('Fumiste', 'fumiste', 'Bâtiment', '🔥'),
  ('Ramoneur', 'ramoneur', 'Bâtiment', '🏭'),
  ('Puisatier', 'puisatier', 'Bâtiment', '🕳️'),
  ('Foreur', 'foreur', 'Bâtiment', '🛢️'),
  ('Ébéniste', 'ebeniste', 'Fabrication / Production', '🪑'),
  ('Ferronnier d''art', 'ferronnier-d-art', 'Fabrication / Production', '⚒️'),
  ('Chaudronnier', 'chaudronnier', 'Fabrication / Production', '🔨'),
  ('Soudeur', 'soudeur', 'Fabrication / Production', '🔥'),
  ('Tôlier', 'tolier', 'Fabrication / Production', '🔨'),
  ('Tourneur', 'tourneur', 'Fabrication / Production', '⚙️'),
  ('Fraiseur', 'fraiseur', 'Fabrication / Production', '⚙️'),
  ('Ajusteur', 'ajusteur', 'Fabrication / Production', '🔧'),
  ('Mécanicien de précision', 'mecanicien-de-precision', 'Fabrication / Production', '🔬'),
  ('Bijoutier', 'bijoutier', 'Fabrication / Production', '💍'),
  ('Joaillier', 'joaillier', 'Fabrication / Production', '💎'),
  ('Orfèvre', 'orfevre', 'Fabrication / Production', '🥇'),
  ('Sertisseur', 'sertisseur', 'Fabrication / Production', '💎'),
  ('Horloger', 'horloger', 'Fabrication / Production', '⌚'),
  ('Graveur', 'graveur', 'Fabrication / Production', '✒️'),
  ('Médailleur', 'medailleur', 'Fabrication / Production', '🏅'),
  ('Ferrailleur', 'ferrailleur', 'Fabrication / Production', '🔩'),
  ('Maroquinier', 'maroquinier', 'Fabrication / Production', '👜'),
  ('Sellier', 'sellier', 'Fabrication / Production', '🐴'),
  ('Bourrelier', 'bourrelier', 'Fabrication / Production', '🐎'),
  ('Cordonnier', 'cordonnier', 'Fabrication / Production', '👞'),
  ('Bottier', 'bottier', 'Fabrication / Production', '👢'),
  ('Coutelier', 'coutelier', 'Fabrication / Production', '🔪'),
  ('Potier', 'potier', 'Fabrication / Production', '🫖'),
  ('Céramiste', 'ceramiste', 'Fabrication / Production', '🏺'),
  ('Porcelainier', 'porcelainier', 'Fabrication / Production', '🍶'),
  ('Verrier', 'verrier', 'Fabrication / Production', '🥃'),
  ('Vitrailliste', 'vitrailliste', 'Fabrication / Production', '🌈'),
  ('Souffleur de verre', 'souffleur-de-verre', 'Fabrication / Production', '🫧'),
  ('Tapissier', 'tapissier', 'Fabrication / Production', '🛋️'),
  ('Encadreur', 'encadreur', 'Fabrication / Production', '🖼️'),
  ('Doreur', 'doreur', 'Fabrication / Production', '✨'),
  ('Relieur', 'relieur', 'Fabrication / Production', '📚'),
  ('Luthier', 'luthier', 'Fabrication / Production', '🎻'),
  ('Facteur d''instruments', 'facteur-d-instruments', 'Fabrication / Production', '🎺'),
  ('Modiste', 'modiste', 'Fabrication / Production', '👒'),
  ('Chapelier', 'chapelier', 'Fabrication / Production', '🎩'),
  ('Couturier', 'couturier', 'Fabrication / Production', '🧵'),
  ('Tailleur', 'tailleur', 'Fabrication / Production', '👔'),
  ('Brodeur', 'brodeur', 'Fabrication / Production', '🪡'),
  ('Dentellier', 'dentellier', 'Fabrication / Production', '🕸️'),
  ('Tisserand', 'tisserand', 'Fabrication / Production', '🧶'),
  ('Teinturier textile', 'teinturier-textile', 'Fabrication / Production', '🌈'),
  ('Sérigraphe', 'serigraphe', 'Fabrication / Production', '🎨'),
  ('Imprimeur', 'imprimeur', 'Fabrication / Production', '🖨️'),
  ('Lithographe', 'lithographe', 'Fabrication / Production', '🪨'),
  ('Typographe', 'typographe', 'Fabrication / Production', '🔠'),
  ('Fabricant de meubles', 'fabricant-de-meubles', 'Fabrication / Production', '🪑'),
  ('Fabricant textile', 'fabricant-textile', 'Fabrication / Production', '🧶'),
  ('Fabricant de jouets', 'fabricant-de-jouets', 'Fabrication / Production', '🧸'),
  ('Fabricant de bougies', 'fabricant-de-bougies', 'Fabrication / Production', '🕯️'),
  ('Savonnier', 'savonnier', 'Fabrication / Production', '🧼'),
  ('Parfumeur artisanal', 'parfumeur-artisanal', 'Fabrication / Production', '🌹'),
  ('Cosméticien artisanal', 'cosmeticien-artisanal', 'Fabrication / Production', '💄'),
  ('Coiffeur', 'coiffeur', 'Services', '💇'),
  ('Barbier', 'barbier', 'Services', '✂️'),
  ('Esthéticienne', 'estheticienne', 'Services', '💅'),
  ('Maquilleur professionnel', 'maquilleur-professionnel', 'Services', '💄'),
  ('Prothésiste ongulaire', 'prothesiste-ongulaire', 'Services', '💅'),
  ('Tatoueur', 'tatoueur', 'Services', '🖋️'),
  ('Perceur', 'perceur', 'Services', '💎'),
  ('Fleuriste', 'fleuriste', 'Services', '💐'),
  ('Toiletteur animalier', 'toiletteur-animalier', 'Services', '🐕'),
  ('Photographe', 'photographe', 'Services', '📷'),
  ('Réparateur informatique', 'reparateur-informatique', 'Services', '💻'),
  ('Dépanneur informatique', 'depanneur-informatique', 'Services', '🖥️'),
  ('Réparateur téléphones', 'reparateur-telephones', 'Services', '📱'),
  ('Réparateur électroménager', 'reparateur-electromenager', 'Services', '🔌'),
  ('Réparateur cycles', 'reparateur-cycles', 'Services', '🚲'),
  ('Réparateur motos', 'reparateur-motos', 'Services', '🏍️'),
  ('Garagiste', 'garagiste', 'Services', '🚗'),
  ('Sellier automobile', 'sellier-automobile', 'Services', '💺'),
  ('Préparateur véhicules', 'preparateur-vehicules', 'Services', '🏎️'),
  ('Contrôleur technique', 'controleur-technique', 'Services', '🔍'),
  ('Dépanneur auto', 'depanneur-auto', 'Services', '🛞'),
  ('Ambulancier', 'ambulancier', 'Services', '🚑'),
  ('Taxi', 'taxi', 'Services', '🚖'),
  ('Chauffeur privé (VTC)', 'chauffeur-prive-vtc', 'Services', '🚙'),
  ('Déménageur', 'demenageur', 'Services', '📦'),
  ('Blanchisseur', 'blanchisseur', 'Services', '🧺'),
  ('Teinturier pressing', 'teinturier-pressing', 'Services', '👕'),
  ('Cordonnier multiservices', 'cordonnier-multiservices', 'Services', '👞'),
  ('Graveur de clés', 'graveur-de-cles', 'Services', '🗝️'),
  ('Serrurier dépannage', 'serrurier-depannage', 'Services', '🔑'),
  ('Accordeur de piano', 'accordeur-de-piano', 'Services', '🎹'),
  ('Maréchal-ferrant', 'marechal-ferrant', 'Services', '🐴'),
  ('Dératiseur', 'deratiseur', 'Services', '🐀'),
  ('Désinsectiseur', 'desinsectiseur', 'Services', '🪳'),
  ('Élagueur', 'elagueur', 'Services', '🌳'),
  ('Paysagiste artisanal', 'paysagiste-artisanal', 'Services', '🌳'),
  ('Jardinier artisanal', 'jardinier-artisanal', 'Services', '🌱'),
  ('Réparateur horlogerie', 'reparateur-horlogerie', 'Services', '⌚'),
  ('Réparateur bijoux', 'reparateur-bijoux', 'Services', '💍'),
  ('Restaurateur de vélos', 'restaurateur-de-velos', 'Services', '🚲'),
  ('Réparateur électronique', 'reparateur-electronique', 'Services', '🔌'),
  ('Installateur antennes', 'installateur-antennes', 'Services', '📡'),
  ('Réparateur chauffage', 'reparateur-chauffage', 'Services', '🔥'),
  ('Réparateur piscines', 'reparateur-piscines', 'Services', '🏊'),
  ('Désinfecteur professionnel', 'desinfecteur-professionnel', 'Services', '🧽'),
  ('Restaurateur de photos anciennes', 'restaurateur-de-photos-anciennes', 'Services', '🖼️')
ON CONFLICT (slug) DO UPDATE SET
  name     = EXCLUDED.name,
  category = EXCLUDED.category,
  icon     = EXCLUDED.icon,
  updated_at = NOW();

-- 3. Reset de la séquence (au cas où)
SELECT setval(pg_get_serial_sequence('public.metiers', 'id'), COALESCE((SELECT MAX(id) FROM public.metiers), 1));

COMMIT;

-- Total : 174 métiers répartis dans 4 catégories :
--   • Alimentation : 26
--   • Bâtiment : 48
--   • Fabrication / Production : 54
--   • Services : 46