export type MetierOption = {
  name: string;
  category: string;
  icon: string;
};

export const METIER_OPTIONS: MetierOption[] = [
  // ═══════════════════════════════════════════════════════════
  // ALIMENTATION
  // ═══════════════════════════════════════════════════════════
  { name: "Boulanger",                        category: "Alimentation", icon: "🥖" },
  { name: "Pâtissier",                        category: "Alimentation", icon: "🧁" },
  { name: "Chocolatier",                      category: "Alimentation", icon: "🍫" },
  { name: "Confiseur",                        category: "Alimentation", icon: "🍬" },
  { name: "Glacier",                          category: "Alimentation", icon: "🍦" },
  { name: "Biscuitier",                       category: "Alimentation", icon: "🍪" },
  { name: "Traiteur",                         category: "Alimentation", icon: "🍴" },
  { name: "Boucher",                          category: "Alimentation", icon: "🥩" },
  { name: "Charcutier",                       category: "Alimentation", icon: "🥓" },
  { name: "Poissonnier",                      category: "Alimentation", icon: "🐟" },
  { name: "Fromager",                         category: "Alimentation", icon: "🧀" },
  { name: "Laitier",                          category: "Alimentation", icon: "🥛" },
  { name: "Brasseur artisanal",               category: "Alimentation", icon: "🍺" },
  { name: "Distillateur",                     category: "Alimentation", icon: "🥃" },
  { name: "Liquoriste",                       category: "Alimentation", icon: "🍶" },
  { name: "Torréfacteur",                     category: "Alimentation", icon: "☕" },
  { name: "Fabricant de glaces",              category: "Alimentation", icon: "🍨" },
  { name: "Pizzaïolo",                        category: "Alimentation", icon: "🍕" },
  { name: "Crêpier",                          category: "Alimentation", icon: "🥞" },
  { name: "Nougatier",                        category: "Alimentation", icon: "🍯" },
  { name: "Apiculteur-transformateur",        category: "Alimentation", icon: "🐝" },
  { name: "Fabricant de produits bio",        category: "Alimentation", icon: "🌱" },
  { name: "Fabricant de chocolats",           category: "Alimentation", icon: "🍫" },
  { name: "Fabricant de produits régionaux",  category: "Alimentation", icon: "🇫🇷" },
  { name: "Fabricant de spiritueux",          category: "Alimentation", icon: "🥃" },
  { name: "Saunier",                          category: "Alimentation", icon: "🧂" },

  // ═══════════════════════════════════════════════════════════
  // BÂTIMENT
  // ═══════════════════════════════════════════════════════════
  { name: "Maçon",                            category: "Bâtiment", icon: "🧱" },
  { name: "Couvreur",                         category: "Bâtiment", icon: "🏠" },
  { name: "Zingueur",                         category: "Bâtiment", icon: "🔨" },
  { name: "Charpentier",                      category: "Bâtiment", icon: "🪵" },
  { name: "Menuisier",                        category: "Bâtiment", icon: "🪚" },
  { name: "Éclairagiste",                     category: "Bâtiment", icon: "💡" },
  { name: "Plombier",                         category: "Bâtiment", icon: "🔧" },
  { name: "Chauffagiste",                     category: "Bâtiment", icon: "🔥" },
  { name: "Climaticien",                      category: "Bâtiment", icon: "❄️" },
  { name: "Frigoriste",                       category: "Bâtiment", icon: "🧊" },
  { name: "Électricien",                      category: "Bâtiment", icon: "⚡" },
  { name: "Domoticien",                       category: "Bâtiment", icon: "🏡" },
  { name: "Cuisiniste",                       category: "Bâtiment", icon: "🍴" },
  { name: "Carreleur",                        category: "Bâtiment", icon: "◼️" },
  { name: "Peintre en bâtiment",              category: "Bâtiment", icon: "🎨" },
  { name: "Décorateur intérieur",             category: "Bâtiment", icon: "🛋️" },
  { name: "Façadier",                         category: "Bâtiment", icon: "🏗️" },
  { name: "Étancheur",                        category: "Bâtiment", icon: "💧" },
  { name: "Plâtrier",                         category: "Bâtiment", icon: "🧰" },
  { name: "Staffeur",                         category: "Bâtiment", icon: "🏛️" },
  { name: "Serrurier",                        category: "Bâtiment", icon: "🔐" },
  { name: "Métallier",                        category: "Bâtiment", icon: "🔩" },
  { name: "Ferronnier",                       category: "Bâtiment", icon: "⚒️" },
  { name: "Tailleur de pierre",               category: "Bâtiment", icon: "⛏️" },
  { name: "Marbrier",                         category: "Bâtiment", icon: "💎" },
  { name: "Installateur sanitaire",           category: "Bâtiment", icon: "🚿" },
  { name: "Canalisateur",                     category: "Bâtiment", icon: "🚰" },
  { name: "Terrassier",                       category: "Bâtiment", icon: "🚜" },
  { name: "Pisciniste",                       category: "Bâtiment", icon: "🏊" },
  { name: "Installateur photovoltaïque",      category: "Bâtiment", icon: "☀️" },
  { name: "Installateur thermique",           category: "Bâtiment", icon: "🌡️" },
  { name: "Storiste",                         category: "Bâtiment", icon: "🪟" },
  { name: "Agenceur",                         category: "Bâtiment", icon: "📐" },
  { name: "Poseur de cuisines",               category: "Bâtiment", icon: "🍳" },
  { name: "Poseur de sols",                   category: "Bâtiment", icon: "🟫" },
  { name: "Parqueteur",                       category: "Bâtiment", icon: "🪵" },
  { name: "Chapiste",                         category: "Bâtiment", icon: "⬜" },
  { name: "Vitrier",                          category: "Bâtiment", icon: "🪟" },
  { name: "Miroitier",                        category: "Bâtiment", icon: "🪞" },
  { name: "Constructeur bois",                category: "Bâtiment", icon: "🏠" },
  { name: "Constructeur métallique",          category: "Bâtiment", icon: "🏗️" },
  { name: "Bardeur",                          category: "Bâtiment", icon: "🏗️" },
  { name: "Échafaudeur",                      category: "Bâtiment", icon: "🪜" },
  { name: "Ascensoriste",                     category: "Bâtiment", icon: "🛗" },
  { name: "Fumiste",                          category: "Bâtiment", icon: "🔥" },
  { name: "Ramoneur",                         category: "Bâtiment", icon: "🏭" },
  { name: "Puisatier",                        category: "Bâtiment", icon: "🕳️" },
  { name: "Foreur",                           category: "Bâtiment", icon: "🛢️" },

  // ═══════════════════════════════════════════════════════════
  // FABRICATION / PRODUCTION
  // ═══════════════════════════════════════════════════════════
  { name: "Ébéniste",                         category: "Fabrication / Production", icon: "🪑" },
  { name: "Ferronnier d'art",                 category: "Fabrication / Production", icon: "⚒️" },
  { name: "Chaudronnier",                     category: "Fabrication / Production", icon: "🔨" },
  { name: "Soudeur",                          category: "Fabrication / Production", icon: "🔥" },
  { name: "Tôlier",                           category: "Fabrication / Production", icon: "🔨" },
  { name: "Tourneur",                         category: "Fabrication / Production", icon: "⚙️" },
  { name: "Fraiseur",                         category: "Fabrication / Production", icon: "⚙️" },
  { name: "Ajusteur",                         category: "Fabrication / Production", icon: "🔧" },
  { name: "Mécanicien de précision",          category: "Fabrication / Production", icon: "🔬" },
  { name: "Bijoutier",                        category: "Fabrication / Production", icon: "💍" },
  { name: "Joaillier",                        category: "Fabrication / Production", icon: "💎" },
  { name: "Orfèvre",                          category: "Fabrication / Production", icon: "🥇" },
  { name: "Sertisseur",                       category: "Fabrication / Production", icon: "💎" },
  { name: "Horloger",                         category: "Fabrication / Production", icon: "⌚" },
  { name: "Graveur",                          category: "Fabrication / Production", icon: "✒️" },
  { name: "Médailleur",                       category: "Fabrication / Production", icon: "🏅" },
  { name: "Ferrailleur",                      category: "Fabrication / Production", icon: "🔩" },
  { name: "Maroquinier",                      category: "Fabrication / Production", icon: "👜" },
  { name: "Sellier",                          category: "Fabrication / Production", icon: "🐴" },
  { name: "Bourrelier",                       category: "Fabrication / Production", icon: "🐎" },
  { name: "Cordonnier",                       category: "Fabrication / Production", icon: "👞" },
  { name: "Bottier",                          category: "Fabrication / Production", icon: "👢" },
  { name: "Coutelier",                        category: "Fabrication / Production", icon: "🔪" },
  { name: "Potier",                           category: "Fabrication / Production", icon: "🫖" },
  { name: "Céramiste",                        category: "Fabrication / Production", icon: "🏺" },
  { name: "Porcelainier",                     category: "Fabrication / Production", icon: "🍶" },
  { name: "Verrier",                          category: "Fabrication / Production", icon: "🥃" },
  { name: "Vitrailliste",                     category: "Fabrication / Production", icon: "🌈" },
  { name: "Souffleur de verre",               category: "Fabrication / Production", icon: "🫧" },
  { name: "Tapissier",                        category: "Fabrication / Production", icon: "🛋️" },
  { name: "Encadreur",                        category: "Fabrication / Production", icon: "🖼️" },
  { name: "Doreur",                           category: "Fabrication / Production", icon: "✨" },
  { name: "Relieur",                          category: "Fabrication / Production", icon: "📚" },
  { name: "Luthier",                          category: "Fabrication / Production", icon: "🎻" },
  { name: "Facteur d'instruments",            category: "Fabrication / Production", icon: "🎺" },
  { name: "Modiste",                          category: "Fabrication / Production", icon: "👒" },
  { name: "Chapelier",                        category: "Fabrication / Production", icon: "🎩" },
  { name: "Couturier",                        category: "Fabrication / Production", icon: "🧵" },
  { name: "Tailleur",                         category: "Fabrication / Production", icon: "👔" },
  { name: "Brodeur",                          category: "Fabrication / Production", icon: "🪡" },
  { name: "Dentellier",                       category: "Fabrication / Production", icon: "🕸️" },
  { name: "Tisserand",                        category: "Fabrication / Production", icon: "🧶" },
  { name: "Teinturier textile",               category: "Fabrication / Production", icon: "🌈" },
  { name: "Sérigraphe",                       category: "Fabrication / Production", icon: "🎨" },
  { name: "Imprimeur",                        category: "Fabrication / Production", icon: "🖨️" },
  { name: "Lithographe",                      category: "Fabrication / Production", icon: "🪨" },
  { name: "Typographe",                       category: "Fabrication / Production", icon: "🔠" },
  { name: "Fabricant de meubles",             category: "Fabrication / Production", icon: "🪑" },
  { name: "Fabricant textile",                category: "Fabrication / Production", icon: "🧶" },
  { name: "Fabricant de jouets",              category: "Fabrication / Production", icon: "🧸" },
  { name: "Fabricant de bougies",             category: "Fabrication / Production", icon: "🕯️" },
  { name: "Savonnier",                        category: "Fabrication / Production", icon: "🧼" },
  { name: "Parfumeur artisanal",              category: "Fabrication / Production", icon: "🌹" },
  { name: "Cosméticien artisanal",            category: "Fabrication / Production", icon: "💄" },

  // ═══════════════════════════════════════════════════════════
  // SERVICES
  // ═══════════════════════════════════════════════════════════
  { name: "Coiffeur",                         category: "Services", icon: "💇" },
  { name: "Barbier",                          category: "Services", icon: "✂️" },
  { name: "Esthéticienne",                    category: "Services", icon: "💅" },
  { name: "Maquilleur professionnel",         category: "Services", icon: "💄" },
  { name: "Prothésiste ongulaire",            category: "Services", icon: "💅" },
  { name: "Tatoueur",                         category: "Services", icon: "🖋️" },
  { name: "Perceur",                          category: "Services", icon: "💎" },
  { name: "Fleuriste",                        category: "Services", icon: "💐" },
  { name: "Toiletteur animalier",             category: "Services", icon: "🐕" },
  { name: "Photographe",                      category: "Services", icon: "📷" },
  { name: "Développeur informatique",         category: "Services", icon: "💻" },
  { name: "Réparateur informatique",          category: "Services", icon: "💻" },
  { name: "Dépanneur informatique",           category: "Services", icon: "🖥️" },
  { name: "Réparateur téléphones",            category: "Services", icon: "📱" },
  { name: "Réparateur électroménager",        category: "Services", icon: "🔌" },
  { name: "Réparateur cycles",                category: "Services", icon: "🚲" },
  { name: "Réparateur motos",                 category: "Services", icon: "🏍️" },
  { name: "Garagiste",                        category: "Services", icon: "🚗" },
  { name: "Sellier automobile",               category: "Services", icon: "💺" },
  { name: "Préparateur véhicules",            category: "Services", icon: "🏎️" },
  { name: "Contrôleur technique",             category: "Services", icon: "🔍" },
  { name: "Dépanneur auto",                   category: "Services", icon: "🛞" },
  { name: "Ambulancier",                      category: "Services", icon: "🚑" },
  { name: "Taxi",                             category: "Services", icon: "🚖" },
  { name: "Chauffeur privé (VTC)",            category: "Services", icon: "🚙" },
  { name: "Déménageur",                       category: "Services", icon: "📦" },
  { name: "Blanchisseur",                     category: "Services", icon: "🧺" },
  { name: "Teinturier pressing",              category: "Services", icon: "👕" },
  { name: "Cordonnier multiservices",         category: "Services", icon: "👞" },
  { name: "Graveur de clés",                  category: "Services", icon: "🗝️" },
  { name: "Serrurier dépannage",              category: "Services", icon: "🔑" },
  { name: "Accordeur de piano",               category: "Services", icon: "🎹" },
  { name: "Maréchal-ferrant",                 category: "Services", icon: "🐴" },
  { name: "Dératiseur",                       category: "Services", icon: "🐀" },
  { name: "Désinsectiseur",                   category: "Services", icon: "🪳" },
  { name: "Élagueur",                         category: "Services", icon: "🌳" },
  { name: "Paysagiste artisanal",             category: "Services", icon: "🌳" },
  { name: "Jardinier artisanal",              category: "Services", icon: "🌱" },
  { name: "Réparateur horlogerie",            category: "Services", icon: "⌚" },
  { name: "Réparateur bijoux",                category: "Services", icon: "💍" },
  { name: "Restaurateur de vélos",            category: "Services", icon: "🚲" },
  { name: "Réparateur électronique",          category: "Services", icon: "🔌" },
  { name: "Installateur antennes",            category: "Services", icon: "📡" },
  { name: "Réparateur chauffage",             category: "Services", icon: "🔥" },
  { name: "Réparateur piscines",              category: "Services", icon: "🏊" },
  { name: "Désinfecteur professionnel",       category: "Services", icon: "🧽" },
  { name: "Restaurateur de photos anciennes", category: "Services", icon: "🖼️" },
];
